[[redirects]]
from = "/youtube/"
to = "https://www.youtube.com/@DominationChronicles"
permanent = true


[[redirects]]
from = "^/new/(.*)"
to = "https://www.youtube.com/@DominationChronicles"
permanent = true